# NetOffice project build definition
version: 2.0.0.{build}

branches:
  only:
    - master
    - /dev.*/
  except:
    - gh-pages
    - import/*


image: Visual Studio 2019

platform: Any CPU
configuration:
  - Debug
  - Release

environment:
  VisualStudioVersion: 16.0

init:
  - ps: |
      (New-Object System.Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/89b627fa-743a-42a0-84d4-cedabdbd194d/bc50e5cf1d6d207a27010bba6233a862/vs_community.exe',"$env:TEMP\vs_community.exe")
      Invoke-Command -ScriptBlock { & "$env:TEMP\vs_community.exe" --quiet --wait --norestart --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetCoreTools }
  - ps: |
      (New-Object System.Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/4d2dfaa1-4f9c-4526-bb6f-117d9d8bbd0e/a9fc9994c1b4d485ab41632b81bf4f56/dotnet-sdk-3.0.100-preview6-012264-win-x64.exe',"$env:TEMP\dotnet-sdk-3.0.100-preview6-012264-win-x64.exe")
      Invoke-Command -ScriptBlock { & "$env:TEMP\dotnet-sdk-3.0.100-preview6-012264-win-x64.exe" /S /v /qn }
  - git config --global core.autocrlf true


build_script:
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild.exe Source\NetOffice.sln /Target:Build;Pack /Verbosity:normal /logger:%MSBuildLogger%

before_build:
  - appveyor-retry nuget restore Source\NetOffice.sln

artifacts:
  - path: 'Source\**\bin\%CONFIGURATION%\*.nupkg'
    name: NetOffice Packages
