# NetOffice project build pipeline

pool:
  vmImage: 'windows-2019'

variables:
  solution: Source/NetOffice.sln
  buildPlatform: Any CPU
  buildConfiguration: Debug
  VersionSuffix: 'alpha-$(Build.BuildId)'
  BuildNumber: $(Build.BuildId)

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 3.0 Preview6'
  inputs:
    packageType: sdk
    version: 3.0.100-preview6-012264
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build NetOffice
  inputs:
    solution: '$(solution)'
    vsVersion: '16.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Build;Pack /p:VersionSuffix="$(VersionSuffix)" /p:BuildNumber="$(BuildNumber)"'
    createLogFile: true
    logFileVerbosity: 'detailed'

- task: PublishBuildArtifacts@1
  displayName: Publish NetOffice assemblies
  inputs:
    pathtoPublish: 'Source\ClientApplication\bin\$(buildConfiguration)'
    artifactName: 'NetOffice Assemblies'

- task: PublishBuildArtifacts@1
  displayName: Publish NetOffice artifacts
  inputs:
    pathtoPublish: 'artifacts'
    artifactName: 'NetOffice packages'

- task: NuGetCommand@2
  displayName: Push NetOffice packages to MyGet.org
  inputs:
    command: push
    packagesToPush: 'artifacts/**/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'MyGet NetOffice feed'
